### PR TITLE
docs: 📝  Update README docs

### PR DESCRIPTION
**Pull request by prashant-shahi**
@pranay01 we would have to integrate **CircleCI** and **Codecov** for their respective badges.

### CODE REVIEW

**Comment by makeavish** [comment]
@prashant-shahi I don't think CircleCI and Codecov badges are necessary until we integrate them to our flow.

**Comment by makeavish** [comment]
Should we also add build commands for external contributors?

**Comment by prashant-shahi** [comment]
> I don't think CircleCI and Codecov badges are necessary until we integrate them to our flow.

@makeavish CircleCI we can skip since, we are already using GH Workflow. Codecov would be nice to have.


> Should we also add build commands for external contributors?

We should add build commands.. for both internal and external contributors.. 😄 
But where? Can we include in README page?

**Comment by pranay01** [comment]
@ankitnayan Can you take a look at this and take a call

**Review by ankitnayan — APPROVED** [review]

**Comment by ankitnayan** [comment]
> @ankitnayan Can you take a look at this and take a call

the build commands for contributors are not needed for now. We will be mostly syncing with upstream.

**Pull request merged**
