### PR TITLE
feat: add gRPC code and method columns

### PR DESCRIPTION
**Pull request by makeavish**

### CODE REVIEW

**Comment by ankitnayan** [comment]
@makeavish we should maintain a new branch for each release like we have in `signoz/signoz`. For this repo, it can be `signoz-v0.43.0.1` to maintain signoz release?
@prashant-shahi please suggest.

**Comment by ankitnayan** [comment]
> @makeavish we should maintain a new branch for each release like we have in `signoz/signoz`. For this repo, it can be `signoz-v0.43.0.1` to maintain signoz release? @prashant-shahi please suggest.

@prashant-shahi Or should we merge to `signoz-v0.43.0` and maintain different tag for different releases like `0.43.0.1`?

**Comment by makeavish** [comment]
@ankitnayan Or we can have tags like `0.43.0-0.8.0` where suffix after `-` denotes the current query-service version with which otel collector is compatible

**Comment by ankitnayan** [comment]
but I think query-service changes much faster than otel-collector. What should we do for that? Try to find any relevant discussion somewhere and @prashant-shahi might have some inputs on this

**Comment by prashant-shahi** [comment]
@ankitnayan @makeavish we need a separate branch which we set as default for the repository.

For the default development branch, we can go ahead with `develop`. We will merge the latest changes in that branch.
We will fork release branches from `develop` and make RC and stable release from the branch

Also, we can easily sync our `main` branch with OpenTelemetry Collector's particular release branch, and further we can locally rebase to `develop` and resolve merge conflicts if any arises.

For versioning format, `0.43.0.1` is not SemVer complaint versioning, however there are other tools which uses that format where the last number is used for "revision".

Other SemVer complaint versioning alternatives:
- `0.43.0-signoz0.7.6` or `0.43.0-signoz-0.7.6`: If we make new SigNoz `OtelCollector` release if and only if there is new SigNoz release.
- `0.43.0-signoz.1` : build number which is ever incrementing
- `0.43.0-signoz.0.7` : separate major and minor versioning for the fork: for each release with non-compatible changes, we would bump up the major version, for every other release, we would only bump up the minor version

_*Note: If we remove `signoz` keyword from the above SemVer complaint versions and they would still be valid._

**Pull request merged**
